### ISSUE TITLE
extDB2 Support

### ISSUE THREAD

**Issue by MitzelLP** [DeadP4xel/SealDrop-AltisLife#10]
Hallo,

Ich habe eine kurze frage, supportet SealDrop ExtDB2? Da leider extDB2 der einzigste Mod ist der Linux unterstützt.

**Comment by DeadP4xel** [comment]
Hallo,

momentan nur bis Version 35 / extDB.

Die Version kannst du hier finden: 
https://github.com/dcorbe/extdb

**Comment by MitzelLP** [comment]
Ich habe diese extdb version installiert, aber ich kann leider den Fehler nicht finden. Ich starte den Server, connecte und bin in der Teamauswahl von Altis. Ich starte das Spiel und lande wieder in der Auswahl.

Währe es möglich das die extdb version kein Debian 8 unterstützt, alle zugehörigen packages sind installiert.


[arma3-server-console.txt](https://github.com/DeadP4xel/SealDrop-AltisLife/files/80076/arma3-server-console.txt)
