### ISSUE TITLE
Civilians Can't Open Y Menu

### ISSUE THREAD

**Issue by TheTwelfthDoctor** [DeadP4xel/SealDrop-AltisLife#17]
Recently set up the mission file and everything on my server but I'm having one issue, Civilians can't open the Y menu. Cops and Medics can perfectly fine but the civilian faction just... can't do it. I don't know why. I don't know if I did something wrong or if it's possibly a MySQL or extDB2 issue. 

One more thing, the intro where you're in the clouds and you zoom into your character which happens when I load in as a cop or a medic doesn't play when I load in as a civilian.

Thanks in advance.

**Comment by jjelliott182** [comment]
I have this problem aswell.

**Comment by cpfox** [comment]
Im having the same problem why is could you help me out DeadP4xel
