### ISSUE TITLE
First Spawn Bug.

### ISSUE THREAD

**Issue by Er1807lp** [DeadP4xel/SealDrop-AltisLife#18]
Der Bug wenn man das erste mal spawnt scheint von /core/welcome.sqf zu kommen. Ich denke das der Grund ist da dieser 
`waitUntil{!isNull (findDisplay 38500)}; //Wait for the spawn selection to be open.
	 waitUntil{isNull (findDisplay 38500)}; //Wait for the spawn selection to be done.`
doppelt ausgeführt wird. einmal in der initciv.sqf und ebenfalls in der welcome.sqf 
Da das Spawnmenu welches durch `[] call life_fnc_spawnMenu;` in initciv.sqf nur einmal ausgeführt wird kann nur die erste Abfrage von 
`waitUntil{!isNull (findDisplay 38500)}; //Wait for the spawn selection to be open.
	 waitUntil{isNull (findDisplay 38500)}; //Wait for the spawn selection to be done.`
abgeschlossen werden. Es sollte warscheinlich reichen in der welcome.sqf diesen teil des Codes zu entfernen.

**Comment by DeadP4xel** [comment]
Hey,

hast du den Bug den mit deiner Fehlerbeschreibung fixen können? Dann werde ich gleich das Repo updaten.

**Comment by Er1807lp** [comment]
Ja dies hat den Fehler behoben. Man kann das Z Inventar wieder öffnen und man bekommt die welcome Nachricht.

**Comment by Er1807lp** [comment]
Ich glaube du hast die falsche Datei bearbeitet. Meinte:
https://github.com/DeadP4xel/SealDrop-AltisLife/blob/master/Server%20Files/Altis_Life.Altis/core/fn_welcome.sqf

Du hast aber 
https://github.com/DeadP4xel/SealDrop-AltisLife/blob/master/Server%20Files/Altis_Life.Altis/script/welcome.sqf

bearbeitet. XD

**Comment by DeadP4xel** [comment]
Nun sollte es erledigt sein.

**Comment by Er1807lp** [comment]
Gut werde später schaun ob die eine zuviel geänderte Datei was kapputmacht
#closed
