### ISSUE TITLE
life_server\Functions\Systems\fn_ajustprices.sqf, line 48

### ISSUE THREAD

**Issue by majoess** [DeadP4xel/SealDrop-AltisLife#7]
2015/08/23, 22:33:05 Error in expression <
if (((_queryResult select 0) select 0) == 0) exitwith {};

_group = ((_queryRes>
2015/08/23, 22:33:05   Error position: <== 0) exitwith {};

_group = ((_queryRes>
2015/08/23, 22:33:05   Error Generic error in expression
2015/08/23, 22:33:05 File life_server\Functions\Systems\fn_ajustprices.sqf, line 48

Sicherlich nicht gewollt oder?

**Comment by majoess** [comment]
Willst du das nicht langsam mal fixen? Ich habe zwar keinen Altis Life Server, allerdings würde es Anfängern schon helfen!

**Comment by Gotteshand** [comment]
Hi Zusammen.

Habe selbe Fehlermeldung und leider weiß ich nicht wie ich es Lösen kann.

10:15:34 "------------- Client Query Request -------------"
10:15:34 "QUERY: SELECT factor FROM economy WHERE ressource='water'"
10:15:34 "Time to complete: 0.0380859 (in seconds)"
10:15:34 "Result: [["0"]]"
10:15:34 "------------------------------------------------"
10:15:34 Error in expression <
if (((_queryResult select 0) select 0) == 0) exitwith {};

_group = ((_queryRes>
10:15:34   Error position: <== 0) exitwith {};

_group = ((_queryRes>
10:15:34   Error Generic error in expression
10:15:34 File life_server\Functions\Systems\fn_ajustprices.sqf, line 48
10:15:34 "------------- Client Query Request -------------"
10:15:34 "QUERY: SELECT ressource, buyprice, sellprice FROM economy WHERE shoptype='market' "
10:15:34 "Time to complete: 0.0390625 (in seconds)"
10:15:34 "Result: [["apple",150,50],["rabbit",170,100],["water",100,0],["tbacon",200,150],["lockpick",33000,15000],["redgull",10600,10000],["peach",150,55],["fuelF",5000,100],["blastingcharge",50000,10000],["boltcutter",30000,25000],["storagesmall",250000,10],["storagebig",500000,10],["pickaxe",9400,8900],["grapes",95,70],["battery",100,50],["zipties",18000,500]]"
10:15:34 "------------------------------------------------"
10:15:36 Server: Object 2:4774 not found (message Type_91)
10:15:37 "civ_2   1    market    5      170      rabbit"
10:15:37 "This transaction doesn't update the price!"
10:15:37 "civ_2   0    market"
10:15:38 "------------- Client Query Request -------------"

etc. Vielen Dank
